<?php
// This script and data application were generated by AppGini 5.23
// Download AppGini for free from http://bigprof.com/appgini/download/

	$currDir=dirname(__FILE__);
	include("$currDir/defaultLang.php");
	include("$currDir/language.php");
	include("$currDir/lib.php");

	header("Content-type: text/javascript; charset=UTF-8");

	$mfk=$_GET['mfk'];
	$id=makeSafe($_GET['id']);
	$rnd1=intval($_GET['rnd1']); if(!$rnd1) $rnd1='';

	if(!$mfk){
		die('// no js code available!');
	}

	switch($mfk){

		case 'outcome':
			if(!$id){
				?>
				$('outcome_area<?php echo $rnd1; ?>').innerHTML='&nbsp;';
				<?php
				break;
			}
			$res = sql("SELECT `outcomes`.`outcome_id` as 'outcome_id', IF(    CHAR_LENGTH(`outcome_areas1`.`name`), CONCAT_WS('',   `outcome_areas1`.`name`), '') as 'outcome_area', `outcomes`.`description` as 'description', `outcomes`.`strata` as 'strata' FROM `outcomes` LEFT JOIN `outcome_areas` as outcome_areas1 ON `outcome_areas1`.`outcome_area_id`=`outcomes`.`outcome_area`  WHERE `outcomes`.`outcome_id`='$id' limit 1", $eo);
			$row = mysql_fetch_assoc($res);
			?>
			$('outcome_area<?php echo $rnd1; ?>').innerHTML = '<?php echo addslashes(str_replace(array("\r", "\n"), '', nl2br($row['outcome_area']))); ?>&nbsp;';
			<?php
			break;


	}

?>