<?php
// This script and data application were generated by AppGini 5.23
// Download AppGini for free from http://bigprof.com/appgini/download/

	$currDir=dirname(__FILE__);
	include("$currDir/defaultLang.php");
	include("$currDir/language.php");
	include("$currDir/lib.php");
	@include("$currDir/hooks/indicators.php");
	include("$currDir/indicators_dml.php");

	// mm: can the current member access this page?
	$perm=getTablePermissions('indicators');
	if(!$perm[0]){
		echo error_message($Translation['tableAccessDenied'], false);
		echo '<script>setTimeout("window.location=\'index.php?signOut=1\'", 2000);</script>';
		exit;
	}

	$x = new DataList;
	$x->TableName = "indicators";

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV=array(   
		"`indicators`.`indicator_id`" => "indicator_id",
		"IF(    CHAR_LENGTH(`outcomes1`.`description`), CONCAT_WS('',   `outcomes1`.`description`), '') /* Outcome */" => "outcome",
		"`indicators`.`description`" => "description"
	);
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = array(   
		1 => '`indicators`.`indicator_id`',
		2 => 2,
		3 => 3
	);

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV=array(   
		"`indicators`.`indicator_id`" => "indicator_id",
		"IF(    CHAR_LENGTH(`outcomes1`.`description`), CONCAT_WS('',   `outcomes1`.`description`), '') /* Outcome */" => "outcome",
		"`indicators`.`description`" => "description"
	);
	// Fields that can be filtered
	$x->QueryFieldsFilters=array(   
		"`indicators`.`indicator_id`" => "Indicator id",
		"IF(    CHAR_LENGTH(`outcomes1`.`description`), CONCAT_WS('',   `outcomes1`.`description`), '') /* Outcome */" => "Outcome",
		"`indicators`.`description`" => "Description"
	);

	// Fields that can be quick searched
	$x->QueryFieldsQS=array(   
		"`indicators`.`indicator_id`" => "indicator_id",
		"IF(    CHAR_LENGTH(`outcomes1`.`description`), CONCAT_WS('',   `outcomes1`.`description`), '') /* Outcome */" => "outcome",
		"`indicators`.`description`" => "description"
	);

	// Lookup fields that can be used as filterers
	$x->filterers = array(  'outcome' => 'Outcome');

	$x->QueryFrom="`indicators` LEFT JOIN `outcomes` as outcomes1 ON `outcomes1`.`outcome_id`=`indicators`.`outcome` ";
	$x->QueryWhere='';
	$x->QueryOrder='';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm[2]==0 ? 1 : 0);
	$x->AllowDelete = $perm[4];
	$x->AllowInsert = $perm[1];
	$x->AllowUpdate = $perm[3];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = 0;
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingMultiSelection = 0;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 1000;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation["quick search"];
	$x->ScriptFileName = "indicators_view.php";
	$x->RedirectAfterInsert = "indicators_view.php?SelectedID=#ID#";
	$x->TableTitle = "Indicators";
	$x->TableIcon = "resources/table_icons/book_keeping.png";
	$x->PrimaryKey = "`indicators`.`indicator_id`";
	$x->DefaultSortField = '1';
	$x->DefaultSortDirection = 'asc';

	$x->ColWidth   = array(  20, 150);
	$x->ColCaption = array("Indicator id", "Description");
	$x->ColFieldName = array('indicator_id', 'description');
	$x->ColNumber  = array(1, 3);

	$x->Template = 'templates/indicators_templateTV.html';
	$x->SelectedTemplate = 'templates/indicators_templateTVS.html';
	$x->ShowTableHeader = 1;
	$x->ShowRecordSlots = 0;
	$x->HighlightColor = '#FFF0C2';

	// mm: build the query based on current member's permissions
	$DisplayRecords = $_REQUEST['DisplayRecords'];
	if(!in_array($DisplayRecords, array('user', 'group'))){ $DisplayRecords = 'all'; }
	if($perm[2]==1 || ($perm[2]>1 && $DisplayRecords=='user' && !$_REQUEST['NoFilter_x'])){ // view owner only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `indicators`.`indicator_id`=membership_userrecords.pkValue and membership_userrecords.tableName='indicators' and lcase(membership_userrecords.memberID)='".getLoggedMemberID()."'";
	}elseif($perm[2]==2 || ($perm[2]>2 && $DisplayRecords=='group' && !$_REQUEST['NoFilter_x'])){ // view group only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `indicators`.`indicator_id`=membership_userrecords.pkValue and membership_userrecords.tableName='indicators' and membership_userrecords.groupID='".getLoggedGroupID()."'";
	}elseif($perm[2]==3){ // view all
		// no further action
	}elseif($perm[2]==0){ // view none
		$x->QueryFields = array("Not enough permissions" => "NEP");
		$x->QueryFrom = '`indicators`';
		$x->QueryWhere = '';
		$x->DefaultSortField = '';
	}
	// hook: indicators_init
	$render=TRUE;
	if(function_exists('indicators_init')){
		$args=array();
		$render=indicators_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: indicators_header
	$headerCode='';
	if(function_exists('indicators_header')){
		$args=array();
		$headerCode=indicators_header($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$headerCode){
		include_once("$currDir/header.php"); 
	}else{
		ob_start(); include_once("$currDir/header.php"); $dHeader=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%HEADER%%>', $dHeader, $headerCode);
	}

	echo $x->HTML;
	// hook: indicators_footer
	$footerCode='';
	if(function_exists('indicators_footer')){
		$args=array();
		$footerCode=indicators_footer($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$footerCode){
		include_once("$currDir/footer.php"); 
	}else{
		ob_start(); include_once("$currDir/footer.php"); $dFooter=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%FOOTER%%>', $dFooter, $footerCode);
	}
?>