<?php
// This script and data application were generated by AppGini 5.23
// Download AppGini for free from http://bigprof.com/appgini/download/

	$currDir=dirname(__FILE__);
	include("$currDir/defaultLang.php");
	include("$currDir/language.php");
	include("$currDir/lib.php");
	@include("$currDir/hooks/outcomes.php");
	include("$currDir/outcomes_dml.php");

	// mm: can the current member access this page?
	$perm=getTablePermissions('outcomes');
	if(!$perm[0]){
		echo error_message($Translation['tableAccessDenied'], false);
		echo '<script>setTimeout("window.location=\'index.php?signOut=1\'", 2000);</script>';
		exit;
	}

	$x = new DataList;
	$x->TableName = "outcomes";

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV=array(   
		"`outcomes`.`outcome_id`" => "outcome_id",
		"IF(    CHAR_LENGTH(`outcome_areas1`.`name`), CONCAT_WS('',   `outcome_areas1`.`name`), '') /* Outcome area */" => "outcome_area",
		"`outcomes`.`description`" => "description",
		"`outcomes`.`strata`" => "strata"
	);
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = array(   
		1 => '`outcomes`.`outcome_id`',
		2 => 2,
		3 => 3,
		4 => 4
	);

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV=array(   
		"`outcomes`.`outcome_id`" => "outcome_id",
		"IF(    CHAR_LENGTH(`outcome_areas1`.`name`), CONCAT_WS('',   `outcome_areas1`.`name`), '') /* Outcome area */" => "outcome_area",
		"`outcomes`.`description`" => "description",
		"`outcomes`.`strata`" => "strata"
	);
	// Fields that can be filtered
	$x->QueryFieldsFilters=array(   
		"`outcomes`.`outcome_id`" => "ID",
		"IF(    CHAR_LENGTH(`outcome_areas1`.`name`), CONCAT_WS('',   `outcome_areas1`.`name`), '') /* Outcome area */" => "Outcome area",
		"`outcomes`.`description`" => "Description",
		"`outcomes`.`strata`" => "Strata"
	);

	// Fields that can be quick searched
	$x->QueryFieldsQS=array(   
		"`outcomes`.`outcome_id`" => "outcome_id",
		"IF(    CHAR_LENGTH(`outcome_areas1`.`name`), CONCAT_WS('',   `outcome_areas1`.`name`), '') /* Outcome area */" => "outcome_area",
		"`outcomes`.`description`" => "description",
		"`outcomes`.`strata`" => "strata"
	);

	// Lookup fields that can be used as filterers
	$x->filterers = array(  'outcome_area' => 'Outcome area');

	$x->QueryFrom="`outcomes` LEFT JOIN `outcome_areas` as outcome_areas1 ON `outcome_areas1`.`outcome_area_id`=`outcomes`.`outcome_area` ";
	$x->QueryWhere='';
	$x->QueryOrder='';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm[2]==0 ? 1 : 0);
	$x->AllowDelete = $perm[4];
	$x->AllowInsert = $perm[1];
	$x->AllowUpdate = $perm[3];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = 0;
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingMultiSelection = 0;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation["quick search"];
	$x->ScriptFileName = "outcomes_view.php";
	$x->RedirectAfterInsert = "outcomes_view.php?SelectedID=#ID#";
	$x->TableTitle = "Outcomes";
	$x->TableIcon = "resources/table_icons/brick.png";
	$x->PrimaryKey = "`outcomes`.`outcome_id`";
	$x->DefaultSortField = '1';
	$x->DefaultSortDirection = 'asc';

	$x->ColWidth   = array(  20, 150, 150, 150);
	$x->ColCaption = array("ID", "Outcome area", "Description", "Strata");
	$x->ColFieldName = array('outcome_id', 'outcome_area', 'description', 'strata');
	$x->ColNumber  = array(1, 2, 3, 4);

	$x->Template = 'templates/outcomes_templateTV.html';
	$x->SelectedTemplate = 'templates/outcomes_templateTVS.html';
	$x->ShowTableHeader = 1;
	$x->ShowRecordSlots = 0;
	$x->HighlightColor = '#FFF0C2';

	// mm: build the query based on current member's permissions
	$DisplayRecords = $_REQUEST['DisplayRecords'];
	if(!in_array($DisplayRecords, array('user', 'group'))){ $DisplayRecords = 'all'; }
	if($perm[2]==1 || ($perm[2]>1 && $DisplayRecords=='user' && !$_REQUEST['NoFilter_x'])){ // view owner only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `outcomes`.`outcome_id`=membership_userrecords.pkValue and membership_userrecords.tableName='outcomes' and lcase(membership_userrecords.memberID)='".getLoggedMemberID()."'";
	}elseif($perm[2]==2 || ($perm[2]>2 && $DisplayRecords=='group' && !$_REQUEST['NoFilter_x'])){ // view group only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `outcomes`.`outcome_id`=membership_userrecords.pkValue and membership_userrecords.tableName='outcomes' and membership_userrecords.groupID='".getLoggedGroupID()."'";
	}elseif($perm[2]==3){ // view all
		// no further action
	}elseif($perm[2]==0){ // view none
		$x->QueryFields = array("Not enough permissions" => "NEP");
		$x->QueryFrom = '`outcomes`';
		$x->QueryWhere = '';
		$x->DefaultSortField = '';
	}
	// hook: outcomes_init
	$render=TRUE;
	if(function_exists('outcomes_init')){
		$args=array();
		$render=outcomes_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: outcomes_header
	$headerCode='';
	if(function_exists('outcomes_header')){
		$args=array();
		$headerCode=outcomes_header($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$headerCode){
		include_once("$currDir/header.php"); 
	}else{
		ob_start(); include_once("$currDir/header.php"); $dHeader=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%HEADER%%>', $dHeader, $headerCode);
	}

	echo $x->HTML;
	// hook: outcomes_footer
	$footerCode='';
	if(function_exists('outcomes_footer')){
		$args=array();
		$footerCode=outcomes_footer($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$footerCode){
		include_once("$currDir/footer.php"); 
	}else{
		ob_start(); include_once("$currDir/footer.php"); $dFooter=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%FOOTER%%>', $dFooter, $footerCode);
	}
?>