<?php
// This script and data application were generated by AppGini 5.23
// Download AppGini for free from http://bigprof.com/appgini/download/

	$currDir=dirname(__FILE__);
	include("$currDir/defaultLang.php");
	include("$currDir/language.php");
	include("$currDir/lib.php");
	@include("$currDir/hooks/outcome_areas.php");
	include("$currDir/outcome_areas_dml.php");

	// mm: can the current member access this page?
	$perm=getTablePermissions('outcome_areas');
	if(!$perm[0]){
		echo error_message($Translation['tableAccessDenied'], false);
		echo '<script>setTimeout("window.location=\'index.php?signOut=1\'", 2000);</script>';
		exit;
	}

	$x = new DataList;
	$x->TableName = "outcome_areas";

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV=array(   
		"`outcome_areas`.`outcome_area_id`" => "outcome_area_id",
		"`outcome_areas`.`name`" => "name",
		"`outcome_areas`.`description`" => "description"
	);
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = array(   
		1 => '`outcome_areas`.`outcome_area_id`',
		2 => 2,
		3 => 3
	);

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV=array(   
		"`outcome_areas`.`outcome_area_id`" => "outcome_area_id",
		"`outcome_areas`.`name`" => "name",
		"`outcome_areas`.`description`" => "description"
	);
	// Fields that can be filtered
	$x->QueryFieldsFilters=array(   
		"`outcome_areas`.`outcome_area_id`" => "ID",
		"`outcome_areas`.`name`" => "Name",
		"`outcome_areas`.`description`" => "Description"
	);

	// Fields that can be quick searched
	$x->QueryFieldsQS=array(   
		"`outcome_areas`.`outcome_area_id`" => "outcome_area_id",
		"`outcome_areas`.`name`" => "name",
		"`outcome_areas`.`description`" => "description"
	);

	// Lookup fields that can be used as filterers
	$x->filterers = array();

	$x->QueryFrom="`outcome_areas` ";
	$x->QueryWhere='';
	$x->QueryOrder='';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm[2]==0 ? 1 : 0);
	$x->AllowDelete = $perm[4];
	$x->AllowInsert = $perm[1];
	$x->AllowUpdate = $perm[3];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = 0;
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingMultiSelection = 0;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation["quick search"];
	$x->ScriptFileName = "outcome_areas_view.php";
	$x->RedirectAfterInsert = "outcome_areas_view.php?SelectedID=#ID#";
	$x->TableTitle = "Outcome areas";
	$x->TableIcon = "resources/table_icons/bricks.png";
	$x->PrimaryKey = "`outcome_areas`.`outcome_area_id`";
	$x->DefaultSortField = '1';
	$x->DefaultSortDirection = 'asc';

	$x->ColWidth   = array(  20, 150, 150);
	$x->ColCaption = array("ID", "Name", "Description");
	$x->ColFieldName = array('outcome_area_id', 'name', 'description');
	$x->ColNumber  = array(1, 2, 3);

	$x->Template = 'templates/outcome_areas_templateTV.html';
	$x->SelectedTemplate = 'templates/outcome_areas_templateTVS.html';
	$x->ShowTableHeader = 1;
	$x->ShowRecordSlots = 0;
	$x->HighlightColor = '#FFF0C2';

	// mm: build the query based on current member's permissions
	$DisplayRecords = $_REQUEST['DisplayRecords'];
	if(!in_array($DisplayRecords, array('user', 'group'))){ $DisplayRecords = 'all'; }
	if($perm[2]==1 || ($perm[2]>1 && $DisplayRecords=='user' && !$_REQUEST['NoFilter_x'])){ // view owner only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `outcome_areas`.`outcome_area_id`=membership_userrecords.pkValue and membership_userrecords.tableName='outcome_areas' and lcase(membership_userrecords.memberID)='".getLoggedMemberID()."'";
	}elseif($perm[2]==2 || ($perm[2]>2 && $DisplayRecords=='group' && !$_REQUEST['NoFilter_x'])){ // view group only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `outcome_areas`.`outcome_area_id`=membership_userrecords.pkValue and membership_userrecords.tableName='outcome_areas' and membership_userrecords.groupID='".getLoggedGroupID()."'";
	}elseif($perm[2]==3){ // view all
		// no further action
	}elseif($perm[2]==0){ // view none
		$x->QueryFields = array("Not enough permissions" => "NEP");
		$x->QueryFrom = '`outcome_areas`';
		$x->QueryWhere = '';
		$x->DefaultSortField = '';
	}
	// hook: outcome_areas_init
	$render=TRUE;
	if(function_exists('outcome_areas_init')){
		$args=array();
		$render=outcome_areas_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: outcome_areas_header
	$headerCode='';
	if(function_exists('outcome_areas_header')){
		$args=array();
		$headerCode=outcome_areas_header($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$headerCode){
		include_once("$currDir/header.php"); 
	}else{
		ob_start(); include_once("$currDir/header.php"); $dHeader=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%HEADER%%>', $dHeader, $headerCode);
	}

	echo $x->HTML;
	// hook: outcome_areas_footer
	$footerCode='';
	if(function_exists('outcome_areas_footer')){
		$args=array();
		$footerCode=outcome_areas_footer($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$footerCode){
		include_once("$currDir/footer.php"); 
	}else{
		ob_start(); include_once("$currDir/footer.php"); $dFooter=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%FOOTER%%>', $dFooter, $footerCode);
	}
?>