<?php
// This script and data application were generated by AppGini 5.23
// Download AppGini for free from http://bigprof.com/appgini/download/

	/* Configuration */
	/*************************************/

		$pcConfig = array(
			'clients' => array(   
			),
			'companies' => array(   
				'client' => array(   
					'parent-table' => 'clients',
					'parent-primary-key' => 'client_id',
					'child-primary-key' => 'company_id',
					'child-primary-key-index' => 0,
					'tab-label' => 'Companies',
					'table-icon' => 'resources/table_icons/chair.png',
					'display-refresh' => true,
					'display-add-new' => true,
					'forced-where' => '',
					'display-fields' => array(0 => 'ID', 1 => 'Name', 2 => 'Client', 3 => 'Website', 11 => 'Date created', 12 => 'Created by'),
					'display-field-names' => array(0 => 'company_id', 1 => 'name', 2 => 'client', 3 => 'website', 11 => 'created', 12 => 'created_by'),
					'sortable-fields' => array(0 => '1', 1 => '2', 2 => '3', 3 => '4', 11 => '`companies`.`created`', 12 => '13'),
					'records-per-page' => 10,
					'default-sort-by' => false,
					'default-sort-direction' => 'asc',
					'open-detail-view-on-click' => true,
					'display-page-selector' => true,
					'show-page-progress' => true,
					'template' => 'children-companies',
					'query' => "SELECT `companies`.`company_id` as 'company_id', `companies`.`name` as 'name', IF(    CHAR_LENGTH(`clients1`.`name`), CONCAT_WS('',   `clients1`.`name`), '') as 'client', `companies`.`website` as 'website', `companies`.`industry` as 'industry', `companies`.`company_number` as 'company_number', `companies`.`country_hq` as 'country_hq', `companies`.`country_operations` as 'country_operations', `companies`.`num_employees` as 'num_employees', `companies`.`company_type` as 'company_type', IF(    CHAR_LENGTH(`sic1`.`code`) || CHAR_LENGTH(`sic1`.`activity`), CONCAT_WS('',   `sic1`.`code`, ' - ', `sic1`.`activity`), '') as 'sic_code', if(`companies`.`created`,date_format(`companies`.`created`,'%d/%m/%Y'),'') as 'created', `companies`.`created_by` as 'created_by' FROM `companies` LEFT JOIN `clients` as clients1 ON `clients1`.`client_id`=`companies`.`client` LEFT JOIN `sic` as sic1 ON `sic1`.`sic_id`=`companies`.`sic_code` "
				)
			),
			'sic' => array(   
			),
			'reports' => array(   
				'company' => array(   
					'parent-table' => 'companies',
					'parent-primary-key' => 'company_id',
					'child-primary-key' => 'report_id',
					'child-primary-key-index' => 0,
					'tab-label' => 'Reports',
					'table-icon' => 'resources/table_icons/application_from_storage.png',
					'display-refresh' => true,
					'display-add-new' => true,
					'forced-where' => '',
					'display-fields' => array(1 => 'Date of Report', 2 => 'Company'),
					'display-field-names' => array(1 => 'date', 2 => 'company'),
					'sortable-fields' => array(1 => '`reports`.`date`', 2 => '3'),
					'records-per-page' => 10,
					'default-sort-by' => false,
					'default-sort-direction' => 'asc',
					'open-detail-view-on-click' => true,
					'display-page-selector' => true,
					'show-page-progress' => true,
					'template' => 'children-reports',
					'query' => "SELECT `reports`.`report_id` as 'report_id', if(`reports`.`date`,date_format(`reports`.`date`,'%d/%m/%Y'),'') as 'date', IF(    CHAR_LENGTH(`companies1`.`name`) || CHAR_LENGTH(`clients1`.`name`), CONCAT_WS('',   `companies1`.`name`, ' - ', `clients1`.`name`), '') as 'company', if(`reports`.`created`,date_format(`reports`.`created`,'%d/%m/%Y'),'') as 'created', `reports`.`created_by` as 'created_by', `reports`.`average_score` as 'average_score' FROM `reports` LEFT JOIN `companies` as companies1 ON `companies1`.`company_id`=`reports`.`company` LEFT JOIN `clients` as clients1 ON `clients1`.`client_id`=`companies1`.`client` "
				)
			),
			'entries' => array(   
				'report' => array(   
					'parent-table' => 'reports',
					'parent-primary-key' => 'report_id',
					'child-primary-key' => 'entry_id',
					'child-primary-key-index' => 0,
					'tab-label' => 'Entries',
					'display-refresh' => true,
					'display-add-new' => true,
					'forced-where' => '',
					'display-fields' => array(0 => 'ID', 1 => 'Created', 2 => 'Created by', 3 => 'Report', 4 => 'Outcome area', 5 => 'Outcome', 7 => 'Score'),
					'display-field-names' => array(0 => 'entry_id', 1 => 'created', 2 => 'created_by', 3 => 'report', 4 => 'outcome_area', 5 => 'outcome', 7 => 'score'),
					'sortable-fields' => array(0 => '1', 1 => '`entries`.`created`', 2 => '3', 3 => '4', 4 => '5', 5 => '6', 7 => '8'),
					'records-per-page' => 10,
					'default-sort-by' => false,
					'default-sort-direction' => 'asc',
					'open-detail-view-on-click' => true,
					'display-page-selector' => true,
					'show-page-progress' => true,
					'template' => 'children-entries',
					'query' => "SELECT `entries`.`entry_id` as 'entry_id', if(`entries`.`created`,date_format(`entries`.`created`,'%d/%m/%Y'),'') as 'created', `entries`.`created_by` as 'created_by', IF(    CHAR_LENGTH(`companies1`.`name`) || CHAR_LENGTH(`clients1`.`name`) || CHAR_LENGTH(`reports1`.`date`), CONCAT_WS('',   `companies1`.`name`, ' - ', `clients1`.`name`, ' - ', `reports1`.`date`), '') as 'report', IF(    CHAR_LENGTH(`outcome_areas1`.`name`), CONCAT_WS('',   `outcome_areas1`.`name`), '') as 'outcome_area', IF(    CHAR_LENGTH(`outcomes1`.`description`), CONCAT_WS('',   `outcomes1`.`description`), '') as 'outcome', IF(    CHAR_LENGTH(`indicators1`.`description`), CONCAT_WS('',   `indicators1`.`description`), '') as 'indicator', `entries`.`score` as 'score', IF(    CHAR_LENGTH(`beneficiary_groups1`.`name`), CONCAT_WS('',   `beneficiary_groups1`.`name`), '') as 'beneficiary_group', `entries`.`beneficiary_group_relevance` as 'beneficiary_group_relevance', `entries`.`comment` as 'comment', `entries`.`reference` as 'reference', `entries`.`reliability` as 'reliability', `entries`.`intentionality` as 'intentionality', `entries`.`equivalence` as 'equivalence' FROM `entries` LEFT JOIN `reports` as reports1 ON `reports1`.`report_id`=`entries`.`report` LEFT JOIN `companies` as companies1 ON `companies1`.`company_id`=`reports1`.`company` LEFT JOIN `clients` as clients1 ON `clients1`.`client_id`=`companies1`.`client` LEFT JOIN `outcomes` as outcomes1 ON `outcomes1`.`outcome_id`=`entries`.`outcome` LEFT JOIN `indicators` as indicators1 ON `indicators1`.`indicator_id`=`entries`.`indicator` LEFT JOIN `beneficiary_groups` as beneficiary_groups1 ON `beneficiary_groups1`.`beneficiary_group_id`=`entries`.`beneficiary_group` LEFT JOIN `outcome_areas` as outcome_areas1 ON `outcome_areas1`.`outcome_area_id`=`outcomes1`.`outcome_area` "
				)
			),
			'outcome_areas' => array(   
			),
			'outcomes' => array(   
			),
			'beneficiary_groups' => array(   
			),
			'indicators' => array(   
			)
		);

	/*************************************/
	/* End of configuration */


	@header("Content-Type: text/html; charset=UTF-8");
	$currDir=dirname(__FILE__);
	include("$currDir/defaultLang.php");
	include("$currDir/language.php");
	include("$currDir/lib.php");

	/**
	* dynamic configuration based on current user's permissions
	* $userPCConfig array is populated only with parent tables where the user has access to
	* at least one child table
	*/
	$userPCConfig = array();
	foreach($pcConfig as $pcChildTable => $ChildrenLookups){
		$permChild = getTablePermissions($pcChildTable);
		if($permChild[2]){ // user can view records of the child table, so proceed to check children lookups
			foreach($ChildrenLookups as $ChildLookupField => $ChildConfig){
				$permParent = getTablePermissions($ChildConfig['parent-table']);
				if($permParent[2]){ // user can view records of parent table
					$userPCConfig[$pcChildTable][$ChildLookupField] = $pcConfig[$pcChildTable][$ChildLookupField];
					// show add new only if configured above AND the user has insert permission
					if($permChild[1] && $pcConfig[$pcChildTable][$ChildLookupField]['display-add-new']){
						$userPCConfig[$pcChildTable][$ChildLookupField]['display-add-new'] = true;
					}else{
						$userPCConfig[$pcChildTable][$ChildLookupField]['display-add-new'] = false;
					}
				}
			}
		}
	}

	/* Receive, UTF-convert, and validate parameters */
	$ParentTable = $_REQUEST['ParentTable']; // needed only with operation=show-children, will be validated in the processing code
	$ChildTable = $_REQUEST['ChildTable'];
		if(!in_array($ChildTable, array_keys($userPCConfig))){
			/* defaults to first child table in config array if not provided */
			$ChildTable = current(array_keys($userPCConfig));
		}
		if(!$ChildTable){ die('<!-- No tables accessible to current user -->'); }
	$SelectedID = $_REQUEST['SelectedID'];
	$ChildLookupField = $_REQUEST['ChildLookupField'];
		if(!in_array($ChildLookupField, array_keys($userPCConfig[$ChildTable]))){
			/* defaults to first lookup in current child config array if not provided */
			$ChildLookupField = current(array_keys($userPCConfig[$ChildTable]));
		}
	$Page = intval($_REQUEST['Page']);
		if($Page < 1){
			$Page = 1;
		}
	$SortBy = ($_REQUEST['SortBy'] != '' ? abs(intval($_REQUEST['SortBy'])) : false);
		if(!in_array($SortBy, array_keys($userPCConfig[$ChildTable][$ChildLookupField]['sortable-fields']), true)){
			$SortBy = $userPCConfig[$ChildTable][$ChildLookupField]['default-sort-by'];
		}
	$SortDirection = strtolower($_REQUEST['SortDirection']);
		if(!in_array($SortDirection, array('asc', 'desc'))){
			$SortDirection = $userPCConfig[$ChildTable][$ChildLookupField]['default-sort-direction'];
		}
	$Operation = strtolower($_REQUEST['Operation']);
		if(!in_array($Operation, array('get-records', 'show-children'))){
			$Operation = 'get-records';
		}

	/* process requested operation */
	switch($Operation){
		/************************************************/
		case 'show-children':
			/* populate HTML and JS content with children tabs */
			$tabLabels = $tabPanels = $tabLoaders = '';
			foreach($userPCConfig as $ChildTable => $childLookups){
				foreach($childLookups as $ChildLookupField => $childConfig){
					if($childConfig['parent-table'] == $ParentTable){
						$TableIcon = ($childConfig['table-icon'] ? "<img src=\"{$childConfig['table-icon']}\" border=\"0\" />" : '');
						$tabLabels .= sprintf('<li%s><a href="#panel_%s-%s" id="tab_%s-%s" data-toggle="tab">%s%s</a></li>' . "\n\t\t\t\t\t",($tabLabels ? '' : ' class="active"'), $ChildTable, $ChildLookupField, $ChildTable, $ChildLookupField, $TableIcon, $childConfig['tab-label']);
						$tabPanels .= sprintf('<div id="panel_%s-%s" class="tab-pane%s"><img src="loading.gif" align="top" />%s</div>' . "\n\t\t\t\t", $ChildTable, $ChildLookupField, ($tabPanels ? '' : ' active'), $Translation['Loading ...']);
						$tabLoaders .= sprintf('post("parent-children.php", { ChildTable: "%s", ChildLookupField: "%s", SelectedID: "%s", Page: 1, SortBy: "", SortDirection: "", Operation: "get-records" }, "panel_%s-%s");' . "\n\t\t\t\t", $ChildTable, $ChildLookupField, addslashes($SelectedID), $ChildTable, $ChildLookupField);
					}
				}
			}

			if(!$tabLabels){ die('<!-- no children of current parent table are accessible to current user -->'); }
			?>
			<div id="children-tabs">
				<ul class="nav nav-tabs">
					<?php echo $tabLabels; ?>
				</ul>
				<span id="pc-loading"></span>
			</div>
			<div class="tab-content"><?php echo $tabPanels; ?></div>

			<script>
				/* ajax loading of each tab's contents */
				<?php echo $tabLoaders; ?>
			</script>
			<?php
			break;

		/************************************************/
		default: /* default is 'get-records' */

			// build the user permissions limiter
			$permissionsWhere = $permissionsJoin = '';
			if($permChild[2] == 1){ // user can view only his own records
				$permissionsWhere = "`$ChildTable`.`{$userPCConfig[$ChildTable][$ChildLookupField]['child-primary-key']}`=`membership_userrecords`.`pkValue` AND `membership_userrecords`.`tableName`='$ChildTable' AND LCASE(`membership_userrecords`.`memberID`)='".getLoggedMemberID()."'";
			}elseif($permChild[2] == 2){ // user can view only his group's records
				$permissionsWhere = "`$ChildTable`.`{$userPCConfig[$ChildTable][$ChildLookupField]['child-primary-key']}`=`membership_userrecords`.`pkValue` AND `membership_userrecords`.`tableName`='$ChildTable' AND `membership_userrecords`.`groupID`='".getLoggedGroupID()."'";
			}elseif($permChild[2] == 3){ // user can view all records
				/* that's the only case remaining ... no need to modify the query in this case */
			}
			$permissionsJoin = ($permissionsWhere ? ", `membership_userrecords`" : '');

			// build the count query
			$forcedWhere = $userPCConfig[$ChildTable][$ChildLookupField]['forced-where'];
			$query = 
				preg_replace('/^select .* from /i', 'SELECT count(1) FROM ', $userPCConfig[$ChildTable][$ChildLookupField]['query']) .
				$permissionsJoin . " WHERE " .
				($permissionsWhere ? "( $permissionsWhere )" : "( 1=1 )") . " AND " .
				($forcedWhere ? "( $forcedWhere )" : "( 2=2 )") . " AND " .
				"`$ChildTable`.`$ChildLookupField`='" . makeSafe($SelectedID) . "'";
			$totalMatches = sqlValue($query);

			// make sure $Page is <= max pages
			$maxPage = ceil($totalMatches / $userPCConfig[$ChildTable][$ChildLookupField]['records-per-page']);
			if($Page > $maxPage){ $Page = $maxPage; }

			// initiate output data array
			$data = array(
				'config' => $userPCConfig[$ChildTable][$ChildLookupField],
				'parameters' => array(
					'ChildTable' => $ChildTable,
					'ChildLookupField' => $ChildLookupField,
					'SelectedID' => $SelectedID,
					'Page' => $Page,
					'SortBy' => $SortBy,
					'SortDirection' => $SortDirection,
					'Operation' => 'get-records'
				),
				'records' => array(),
				'totalMatches' => $totalMatches
			);

			// build the data query
			if($totalMatches){ // if we have at least one record, proceed with fetching data
				$startRecord = $userPCConfig[$ChildTable][$ChildLookupField]['records-per-page'] * ($Page - 1);
				$data['query'] = 
					$userPCConfig[$ChildTable][$ChildLookupField]['query'] .
					$permissionsJoin . " WHERE " .
					($permissionsWhere ? "( $permissionsWhere )" : "( 1=1 )") . " AND " .
					($forcedWhere ? "( $forcedWhere )" : "( 2=2 )") . " AND " .
					"`$ChildTable`.`$ChildLookupField`='" . makeSafe($SelectedID) . "'" . 
					($SortBy !== false && $userPCConfig[$ChildTable][$ChildLookupField]['sortable-fields'][$SortBy] ? " ORDER BY {$userPCConfig[$ChildTable][$ChildLookupField]['sortable-fields'][$SortBy]} $SortDirection" : '') .
					" LIMIT $startRecord, {$userPCConfig[$ChildTable][$ChildLookupField]['records-per-page']}";
				$res = sql($data['query'], $eo);
				while($row = mysql_fetch_row($res)){
					$data['records'][$row[$userPCConfig[$ChildTable][$ChildLookupField]['child-primary-key-index']]] = $row;
				}
			}else{ // if no matching records
				$startRecord = 0;
			}

			$response = loadView($userPCConfig[$ChildTable][$ChildLookupField]['template'], $data);

			// change name space to ensure uniqueness
			$uniqueNameSpace = $ChildTable.ucfirst($ChildLookupField).'GetRecords';
			echo str_replace("{$ChildTable}GetChildrenRecordsList", $uniqueNameSpace, $response);
		/************************************************/
	}
