<?php
// This script and data application were generated by AppGini 5.23
// Download AppGini for free from http://bigprof.com/appgini/download/

	$currDir=dirname(__FILE__);
	include("$currDir/defaultLang.php");
	include("$currDir/language.php");
	include("$currDir/lib.php");
	@include("$currDir/hooks/reports.php");
	include("$currDir/reports_dml.php");

	// mm: can the current member access this page?
	$perm=getTablePermissions('reports');
	if(!$perm[0]){
		echo error_message($Translation['tableAccessDenied'], false);
		echo '<script>setTimeout("window.location=\'index.php?signOut=1\'", 2000);</script>';
		exit;
	}

	$x = new DataList;
	$x->TableName = "reports";

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV=array(   
		"`reports`.`report_id`" => "report_id",
		"if(`reports`.`start_date`,date_format(`reports`.`start_date`,'%d/%m/%Y'),'')" => "start_date",
		"if(`reports`.`end_date`,date_format(`reports`.`end_date`,'%d/%m/%Y'),'')" => "end_date",
		"IF(    CHAR_LENGTH(`companies1`.`name`) || CHAR_LENGTH(`clients1`.`name`), CONCAT_WS('',   `companies1`.`name`, ' - ', `clients1`.`name`), '') /* Company */" => "company",
		"if(`reports`.`created`,date_format(`reports`.`created`,'%d/%m/%Y'),'')" => "created",
		"`reports`.`created_by`" => "created_by",
		"`reports`.`average_score`" => "average_score"
	);
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = array(   
		1 => '`reports`.`report_id`',
		2 => '`reports`.`start_date`',
		3 => '`reports`.`end_date`',
		4 => 4,
		5 => '`reports`.`created`',
		6 => 6,
		7 => '`reports`.`average_score`'
	);

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV=array(   
		"`reports`.`report_id`" => "report_id",
		"if(`reports`.`start_date`,date_format(`reports`.`start_date`,'%d/%m/%Y'),'')" => "start_date",
		"if(`reports`.`end_date`,date_format(`reports`.`end_date`,'%d/%m/%Y'),'')" => "end_date",
		"IF(    CHAR_LENGTH(`companies1`.`name`) || CHAR_LENGTH(`clients1`.`name`), CONCAT_WS('',   `companies1`.`name`, ' - ', `clients1`.`name`), '') /* Company */" => "company",
		"if(`reports`.`created`,date_format(`reports`.`created`,'%d/%m/%Y'),'')" => "created",
		"`reports`.`created_by`" => "created_by",
		"`reports`.`average_score`" => "average_score"
	);
	// Fields that can be filtered
	$x->QueryFieldsFilters=array(   
		"`reports`.`report_id`" => "ID",
		"`reports`.`start_date`" => "Report start date",
		"`reports`.`end_date`" => "Report end date",
		"IF(    CHAR_LENGTH(`companies1`.`name`) || CHAR_LENGTH(`clients1`.`name`), CONCAT_WS('',   `companies1`.`name`, ' - ', `clients1`.`name`), '') /* Company */" => "Company",
		"`reports`.`created`" => "Created",
		"`reports`.`created_by`" => "Created by",
		"`reports`.`average_score`" => "Average score"
	);

	// Fields that can be quick searched
	$x->QueryFieldsQS=array(   
		"`reports`.`report_id`" => "report_id",
		"if(`reports`.`start_date`,date_format(`reports`.`start_date`,'%d/%m/%Y'),'')" => "start_date",
		"if(`reports`.`end_date`,date_format(`reports`.`end_date`,'%d/%m/%Y'),'')" => "end_date",
		"IF(    CHAR_LENGTH(`companies1`.`name`) || CHAR_LENGTH(`clients1`.`name`), CONCAT_WS('',   `companies1`.`name`, ' - ', `clients1`.`name`), '') /* Company */" => "company",
		"if(`reports`.`created`,date_format(`reports`.`created`,'%d/%m/%Y'),'')" => "created",
		"`reports`.`created_by`" => "created_by",
		"`reports`.`average_score`" => "average_score"
	);

	// Lookup fields that can be used as filterers
	$x->filterers = array(  'company' => 'Company');

	$x->QueryFrom="`reports` LEFT JOIN `companies` as companies1 ON `companies1`.`company_id`=`reports`.`company` LEFT JOIN `clients` as clients1 ON `clients1`.`client_id`=`companies1`.`client` ";
	$x->QueryWhere='';
	$x->QueryOrder='';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm[2]==0 ? 1 : 0);
	$x->AllowDelete = $perm[4];
	$x->AllowInsert = $perm[1];
	$x->AllowUpdate = $perm[3];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 1;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = 0;
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingMultiSelection = 0;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation["quick search"];
	$x->ScriptFileName = "reports_view.php";
	$x->RedirectAfterInsert = "reports_view.php?SelectedID=#ID#";
	$x->TableTitle = "Reports";
	$x->TableIcon = "resources/table_icons/application_from_storage.png";
	$x->PrimaryKey = "`reports`.`report_id`";

	$x->ColWidth   = array(  150, 150, 150);
	$x->ColCaption = array("Report start date", "Report end date", "Company");
	$x->ColFieldName = array('start_date', 'end_date', 'company');
	$x->ColNumber  = array(2, 3, 4);

	$x->Template = 'templates/reports_templateTV.html';
	$x->SelectedTemplate = 'templates/reports_templateTVS.html';
	$x->ShowTableHeader = 1;
	$x->ShowRecordSlots = 0;
	$x->HighlightColor = '#FFF0C2';

	// mm: build the query based on current member's permissions
	$DisplayRecords = $_REQUEST['DisplayRecords'];
	if(!in_array($DisplayRecords, array('user', 'group'))){ $DisplayRecords = 'all'; }
	if($perm[2]==1 || ($perm[2]>1 && $DisplayRecords=='user' && !$_REQUEST['NoFilter_x'])){ // view owner only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `reports`.`report_id`=membership_userrecords.pkValue and membership_userrecords.tableName='reports' and lcase(membership_userrecords.memberID)='".getLoggedMemberID()."'";
	}elseif($perm[2]==2 || ($perm[2]>2 && $DisplayRecords=='group' && !$_REQUEST['NoFilter_x'])){ // view group only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `reports`.`report_id`=membership_userrecords.pkValue and membership_userrecords.tableName='reports' and membership_userrecords.groupID='".getLoggedGroupID()."'";
	}elseif($perm[2]==3){ // view all
		// no further action
	}elseif($perm[2]==0){ // view none
		$x->QueryFields = array("Not enough permissions" => "NEP");
		$x->QueryFrom = '`reports`';
		$x->QueryWhere = '';
		$x->DefaultSortField = '';
	}
	// hook: reports_init
	$render=TRUE;
	if(function_exists('reports_init')){
		$args=array();
		$render=reports_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: reports_header
	$headerCode='';
	if(function_exists('reports_header')){
		$args=array();
		$headerCode=reports_header($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$headerCode){
		include_once("$currDir/header.php"); 
	}else{
		ob_start(); include_once("$currDir/header.php"); $dHeader=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%HEADER%%>', $dHeader, $headerCode);
	}

	echo $x->HTML;
	// hook: reports_footer
	$footerCode='';
	if(function_exists('reports_footer')){
		$args=array();
		$footerCode=reports_footer($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$footerCode){
		include_once("$currDir/footer.php"); 
	}else{
		ob_start(); include_once("$currDir/footer.php"); $dFooter=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%FOOTER%%>', $dFooter, $footerCode);
	}
?>