<?php

// Data functions for table tax_entry

// This script and data application were generated by AppGini 5.23
// Download AppGini for free from http://bigprof.com/appgini/download/

function tax_entry_insert(){
	global $Translation;

	if($_GET['insert_x']!=''){$_POST=$_GET;}

	// mm: can member insert record?
	$arrPerm=getTablePermissions('tax_entry');
	if(!$arrPerm[1]){
		return false;
	}

	$data['created'] = parseCode('<%%creationDate%%>', true, true);
	$data['created_by'] = parseCode('<%%creatorUsername%%>', true);
	$data['report'] = makeSafe($_POST['report']);
		if($data['report'] == empty_lookup_value){ $data['report'] = ''; }
	$data['turnover'] = makeSafe($_POST['turnover']);
		if($data['turnover'] == empty_lookup_value){ $data['turnover'] = ''; }
	$data['payroll_tax'] = makeSafe($_POST['payroll_tax']);
		if($data['payroll_tax'] == empty_lookup_value){ $data['payroll_tax'] = ''; }
	$data['ni_contribution'] = makeSafe($_POST['ni_contribution']);
		if($data['ni_contribution'] == empty_lookup_value){ $data['ni_contribution'] = ''; }
	$data['business_rates'] = makeSafe($_POST['business_rates']);
		if($data['business_rates'] == empty_lookup_value){ $data['business_rates'] = ''; }
	$data['corporation_tax'] = makeSafe($_POST['corporation_tax']);
		if($data['corporation_tax'] == empty_lookup_value){ $data['corporation_tax'] = ''; }
	$data['other_tax'] = makeSafe($_POST['other_tax']);
		if($data['other_tax'] == empty_lookup_value){ $data['other_tax'] = ''; }
	$data['sum'] = makeSafe($_POST['sum']);
		if($data['sum'] == empty_lookup_value){ $data['sum'] = ''; }
	$data['ratio'] = makeSafe($_POST['ratio']);
		if($data['ratio'] == empty_lookup_value){ $data['ratio'] = ''; }
	if($data['report']== ''){
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">" . $Translation['error:'] . " 'Report': " . $Translation['field not null'] . '<br /><br />';
		echo '<a href="" onclick="history.go(-1); return false;">'.$Translation['< back'].'</a></div>';
		exit;
	}

	// hook: tax_entry_before_insert
	if(function_exists('tax_entry_before_insert')){
		$args=array();
		if(!tax_entry_before_insert($data, getMemberInfo(), $args)){ return false; }
	}

	$o=array('silentErrors' => true);
	sql('insert into `tax_entry` set       `created`=' . "'{$data['created']}'" . ', `created_by`=' . "'{$data['created_by']}'" . ', `report`=' . (($data['report'] !== '' && $data['report'] !== NULL) ? "'{$data['report']}'" : 'NULL') . ', `turnover`=' . (($data['turnover'] !== '' && $data['turnover'] !== NULL) ? "'{$data['turnover']}'" : 'NULL') . ', `payroll_tax`=' . (($data['payroll_tax'] !== '' && $data['payroll_tax'] !== NULL) ? "'{$data['payroll_tax']}'" : 'NULL') . ', `ni_contribution`=' . (($data['ni_contribution'] !== '' && $data['ni_contribution'] !== NULL) ? "'{$data['ni_contribution']}'" : 'NULL') . ', `business_rates`=' . (($data['business_rates'] !== '' && $data['business_rates'] !== NULL) ? "'{$data['business_rates']}'" : 'NULL') . ', `corporation_tax`=' . (($data['corporation_tax'] !== '' && $data['corporation_tax'] !== NULL) ? "'{$data['corporation_tax']}'" : 'NULL') . ', `other_tax`=' . (($data['other_tax'] !== '' && $data['other_tax'] !== NULL) ? "'{$data['other_tax']}'" : 'NULL') . ', `sum`=' . (($data['sum'] !== '' && $data['sum'] !== NULL) ? "'{$data['sum']}'" : 'NULL') . ', `ratio`=' . (($data['ratio'] !== '' && $data['ratio'] !== NULL) ? "'{$data['ratio']}'" : 'NULL'), $o);
	if($o['error']!=''){
		echo $o['error'];
		echo "<a href=\"tax_entry_view.php?addNew_x=1\">{$Translation['< back']}</a>";
		exit;
	}

	$recID=mysql_insert_id();

	// hook: tax_entry_after_insert
	if(function_exists('tax_entry_after_insert')){
		$res = sql("select * from `tax_entry` where `tax_entry_id`='" . makeSafe($recID) . "' limit 1", $eo);
		if($row = mysql_fetch_assoc($res)){
			$data = array_map('makeSafe', $row);
		}
		$data['selectedID'] = makeSafe($recID);
		$args=array();
		if(!tax_entry_after_insert($data, getMemberInfo(), $args)){ return (get_magic_quotes_gpc() ? stripslashes($recID) : $recID); }
	}

	// mm: save ownership data
	sql("insert into membership_userrecords set tableName='tax_entry', pkValue='$recID', memberID='".getLoggedMemberID()."', dateAdded='".time()."', dateUpdated='".time()."', groupID='".getLoggedGroupID()."'", $eo);

	return (get_magic_quotes_gpc() ? stripslashes($recID) : $recID);
}

function tax_entry_delete($selected_id, $AllowDeleteOfParents=false, $skipChecks=false){
	// insure referential integrity ...
	global $Translation;
	$selected_id=makeSafe($selected_id);

	// mm: can member delete record?
	$arrPerm=getTablePermissions('tax_entry');
	$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='tax_entry' and pkValue='$selected_id'");
	$ownerMemberID=sqlValue("select lcase(memberID) from membership_userrecords where tableName='tax_entry' and pkValue='$selected_id'");
	if(($arrPerm[4]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[4]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[4]==3){ // allow delete?
		// delete allowed, so continue ...
	}else{
		return $Translation['You don\'t have enough permissions to delete this record'];
	}

	// hook: tax_entry_before_delete
	if(function_exists('tax_entry_before_delete')){
		$args=array();
		if(!tax_entry_before_delete($selected_id, $skipChecks, getMemberInfo(), $args))
			return $Translation['Couldn\'t delete this record'];
	}

	sql("delete from `tax_entry` where `tax_entry_id`='$selected_id'", $eo);

	// hook: tax_entry_after_delete
	if(function_exists('tax_entry_after_delete')){
		$args=array();
		tax_entry_after_delete($selected_id, getMemberInfo(), $args);
	}

	// mm: delete ownership data
	sql("delete from membership_userrecords where tableName='tax_entry' and pkValue='$selected_id'", $eo);
}

function tax_entry_update($selected_id){
	global $Translation;

	if($_GET['update_x']!=''){$_POST=$_GET;}

	// mm: can member edit record?
	$arrPerm=getTablePermissions('tax_entry');
	$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='tax_entry' and pkValue='".makeSafe($selected_id)."'");
	$ownerMemberID=sqlValue("select lcase(memberID) from membership_userrecords where tableName='tax_entry' and pkValue='".makeSafe($selected_id)."'");
	if(($arrPerm[3]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[3]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[3]==3){ // allow update?
		// update allowed, so continue ...
	}else{
		return false;
	}

	$data['created'] = parseMySQLDate('', '<%%creationDate%%>');
	$data['report'] = makeSafe($_POST['report']);
		if($data['report'] == empty_lookup_value){ $data['report'] = ''; }
	if($data['report']==''){
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'Report': {$Translation['field not null']}<br /><br />";
		echo '<a href="" onclick="history.go(-1); return false;">'.$Translation['< back'].'</a></div>';
		exit;
	}
	$data['turnover'] = makeSafe($_POST['turnover']);
		if($data['turnover'] == empty_lookup_value){ $data['turnover'] = ''; }
	$data['payroll_tax'] = makeSafe($_POST['payroll_tax']);
		if($data['payroll_tax'] == empty_lookup_value){ $data['payroll_tax'] = ''; }
	$data['ni_contribution'] = makeSafe($_POST['ni_contribution']);
		if($data['ni_contribution'] == empty_lookup_value){ $data['ni_contribution'] = ''; }
	$data['business_rates'] = makeSafe($_POST['business_rates']);
		if($data['business_rates'] == empty_lookup_value){ $data['business_rates'] = ''; }
	$data['corporation_tax'] = makeSafe($_POST['corporation_tax']);
		if($data['corporation_tax'] == empty_lookup_value){ $data['corporation_tax'] = ''; }
	$data['other_tax'] = makeSafe($_POST['other_tax']);
		if($data['other_tax'] == empty_lookup_value){ $data['other_tax'] = ''; }
	$data['sum'] = makeSafe($_POST['sum']);
		if($data['sum'] == empty_lookup_value){ $data['sum'] = ''; }
	$data['ratio'] = makeSafe($_POST['ratio']);
		if($data['ratio'] == empty_lookup_value){ $data['ratio'] = ''; }
	$data['selectedID']=makeSafe($selected_id);

	// hook: tax_entry_before_update
	if(function_exists('tax_entry_before_update')){
		$args=array();
		if(!tax_entry_before_update($data, getMemberInfo(), $args)){ return false; }
	}

	$o=array('silentErrors' => true);
	sql('update `tax_entry` set       `created`=' . (($data['created'] != '') ? "'{$data['created']}'" : 'NULL') . ', `report`=' . (($data['report'] !== '' && $data['report'] !== NULL) ? "'{$data['report']}'" : 'NULL') . ', `turnover`=' . (($data['turnover'] !== '' && $data['turnover'] !== NULL) ? "'{$data['turnover']}'" : 'NULL') . ', `payroll_tax`=' . (($data['payroll_tax'] !== '' && $data['payroll_tax'] !== NULL) ? "'{$data['payroll_tax']}'" : 'NULL') . ', `ni_contribution`=' . (($data['ni_contribution'] !== '' && $data['ni_contribution'] !== NULL) ? "'{$data['ni_contribution']}'" : 'NULL') . ', `business_rates`=' . (($data['business_rates'] !== '' && $data['business_rates'] !== NULL) ? "'{$data['business_rates']}'" : 'NULL') . ', `corporation_tax`=' . (($data['corporation_tax'] !== '' && $data['corporation_tax'] !== NULL) ? "'{$data['corporation_tax']}'" : 'NULL') . ', `other_tax`=' . (($data['other_tax'] !== '' && $data['other_tax'] !== NULL) ? "'{$data['other_tax']}'" : 'NULL') . ', `sum`=' . (($data['sum'] !== '' && $data['sum'] !== NULL) ? "'{$data['sum']}'" : 'NULL') . ', `ratio`=' . (($data['ratio'] !== '' && $data['ratio'] !== NULL) ? "'{$data['ratio']}'" : 'NULL') . " where `tax_entry_id`='".makeSafe($selected_id)."'", $o);
	if($o['error']!=''){
		echo $o['error'];
		echo '<a href="tax_entry_view.php?SelectedID='.urlencode($selected_id)."\">{$Translation['< back']}</a>";
		exit;
	}


	// hook: tax_entry_after_update
	if(function_exists('tax_entry_after_update')){
		$res = sql("SELECT * FROM `tax_entry` WHERE `tax_entry_id`='{$data['selectedID']}' LIMIT 1", $eo);
		if($row = mysql_fetch_assoc($res)){
			$data = array_map('makeSafe', $row);
		}
		$data['selectedID'] = $data['tax_entry_id'];
		$args = array();
		if(!tax_entry_after_update($data, getMemberInfo(), $args)){ return; }
	}

	// mm: update ownership data
	sql("update membership_userrecords set dateUpdated='".time()."' where tableName='tax_entry' and pkValue='".makeSafe($selected_id)."'", $eo);

}

function tax_entry_form($selected_id = '', $AllowUpdate = 1, $AllowInsert = 1, $AllowDelete = 1, $ShowCancel = 0){
	// function to return an editable form for a table records
	// and fill it with data of record whose ID is $selected_id. If $selected_id
	// is empty, an empty form is shown, with only an 'Add New'
	// button displayed.

	global $Translation;

	// mm: get table permissions
	$arrPerm=getTablePermissions('tax_entry');
	if(!$arrPerm[1] && $selected_id==''){ return ''; }
	// print preview?
	$dvprint = false;
	if($selected_id && $_REQUEST['dvprint_x'] != ''){
		$dvprint = true;
	}

	$filterer_report = thisOr(undo_magic_quotes($_REQUEST['filterer_report']), '');

	// populate filterers, starting from children to grand-parents

	// unique random identifier
	$rnd1 = ($dvprint ? rand(1000000, 9999999) : '');
	// combobox: created
	$combo_created = new DateCombo;
	$combo_created->DateFormat = "dmy";
	$combo_created->MinYear = 1900;
	$combo_created->MaxYear = 2100;
	$combo_created->DefaultDate = parseMySQLDate('<%%creationDate%%>', '<%%creationDate%%>');
	$combo_created->MonthNames = $Translation['month names'];
	$combo_created->NamePrefix = 'created';
	// combobox: report
	$combo_report = new DataCombo;

	if($selected_id){
		// mm: check member permissions
		if(!$arrPerm[2]){
			return "";
		}
		// mm: who is the owner?
		$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='tax_entry' and pkValue='".makeSafe($selected_id)."'");
		$ownerMemberID=sqlValue("select lcase(memberID) from membership_userrecords where tableName='tax_entry' and pkValue='".makeSafe($selected_id)."'");
		if($arrPerm[2]==1 && getLoggedMemberID()!=$ownerMemberID){
			return "";
		}
		if($arrPerm[2]==2 && getLoggedGroupID()!=$ownerGroupID){
			return "";
		}

		// can edit?
		if(($arrPerm[3]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[3]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[3]==3){
			$AllowUpdate=1;
		}else{
			$AllowUpdate=0;
		}

		$res = sql("select * from `tax_entry` where `tax_entry_id`='".makeSafe($selected_id)."'", $eo);
		$row = mysql_fetch_array($res);
		$urow = $row; /* unsanitized data */
		$hc = new CI_Input();
		$row = $hc->xss_clean($row); /* sanitize data */
		$combo_created->DefaultDate = $row['created'];
		$combo_report->SelectedData = $row['report'];
	}else{
		$combo_report->SelectedData = $filterer_report;
	}
	$combo_report->HTML = $combo_report->MatchText = '<span id="report-container' . $rnd1 . '"></span><input type="hidden" name="report" id="report' . $rnd1 . '">';

	ob_start();
	?>

	<script>
		// initial lookup values
		var current_report__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['report'] : $filterer_report); ?>"};
		
		jQuery(function() {
			report_reload__RAND__();
		});
		function report_reload__RAND__(){
		<?php if(($AllowUpdate || $AllowInsert) && !$dvprint){ ?>

			jQuery("#report-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c){
					jQuery.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: current_report__RAND__.value, t: 'tax_entry', f: 'report' }
					}).done(function(resp){
						c({
							id: resp.results[0].id,
							text: resp.results[0].text
						});
						jQuery('[name="report"]').val(resp.results[0].id);


						if(typeof(report_update_autofills__RAND__) == 'function') report_update_autofills__RAND__();
					});
				},
				width: '100%',
				formatNoMatches: function(term){ return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 10,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page){ return { s: term, p: page, t: 'tax_entry', f: 'report' }; },
					results: function(resp, page){ return resp; }
				}
			}).on('change', function(e){
				current_report__RAND__.value = e.added.id;
				current_report__RAND__.text = e.added.text;
				jQuery('[name="report"]').val(e.added.id);


				if(typeof(report_update_autofills__RAND__) == 'function') report_update_autofills__RAND__();
			});
		<?php }else{ ?>

			jQuery.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: current_report__RAND__.value, t: 'tax_entry', f: 'report' }
			}).done(function(resp){
				jQuery('#report-container__RAND__').html('<span id="report-match-text">' + resp.results[0].text + '</span>');

				if(typeof(report_update_autofills__RAND__) == 'function') report_update_autofills__RAND__();
			});
		<?php } ?>

		}
	</script>
	<?php
	
	$lookups = str_replace('__RAND__', $rnd1, ob_get_contents());
	ob_end_clean();


	// code for template based detail view forms

	// open the detail view template
	if($dvprint){
		$templateCode = @file_get_contents('./templates/tax_entry_templateDVP.html');
	}else{
		$templateCode = @file_get_contents('./templates/tax_entry_templateDV.html');
	}

	// process form title
	$templateCode=str_replace('<%%DETAIL_VIEW_TITLE%%>', 'Tax details', $templateCode);
	$templateCode=str_replace('<%%RND1%%>', $rnd1, $templateCode);
	// process buttons
	if($arrPerm[1]){ // allow insert?
		if(!$selected_id) $templateCode=str_replace('<%%INSERT_BUTTON%%>', '<button tabindex="2" type="submit" class="btn btn-success" id="insert" name="insert_x" value="1" onclick="return tax_entry_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save New'] . '</button>', $templateCode);
		$templateCode=str_replace('<%%INSERT_BUTTON%%>', '<button tabindex="2" type="submit" class="btn btn-default" id="insert" name="insert_x" value="1" onclick="return tax_entry_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save As Copy'] . '</button>', $templateCode);
	}else{
		$templateCode=str_replace('<%%INSERT_BUTTON%%>', '', $templateCode);
	}

	// 'Back' button action
	if($_REQUEST['Embedded']){
		$backAction = 'window.parent.jQuery(\'.modal\').modal(\'hide\'); return false;';
	}else{
		$backAction = '$$(\'form\')[0].writeAttribute(\'novalidate\', \'novalidate\'); document.myform.reset(); return true;';
	}

	if($selected_id){
		if(!$_REQUEST['Embedded']) $templateCode=str_replace('<%%DVPRINT_BUTTON%%>', '<button tabindex="2" type="submit" class="btn btn-default" id="dvprint" name="dvprint_x" value="1" onclick="$$(\'form\')[0].writeAttribute(\'novalidate\', \'novalidate\'); document.myform.reset(); return true;"><i class="glyphicon glyphicon-print"></i> ' . $Translation['Print Preview'] . '</button>', $templateCode);
		if($AllowUpdate){
			$templateCode=str_replace('<%%UPDATE_BUTTON%%>', '<button tabindex="2" type="submit" class="btn btn-success btn-lg" id="update" name="update_x" value="1" onclick="return tax_entry_validateData();"><i class="glyphicon glyphicon-ok"></i> ' . $Translation['Save Changes'] . '</button>', $templateCode);
		}else{
			$templateCode=str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		}
		if(($arrPerm[4]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[4]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[4]==3){ // allow delete?
			$templateCode=str_replace('<%%DELETE_BUTTON%%>', '<button tabindex="2" type="submit" class="btn btn-danger" id="delete" name="delete_x" value="1" onclick="return confirm(\'' . $Translation['are you sure?'] . '\');"><i class="glyphicon glyphicon-trash"></i> ' . $Translation['Delete'] . '</button>', $templateCode);
		}else{
			$templateCode=str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);
		}
		$templateCode=str_replace('<%%DESELECT_BUTTON%%>', '<button tabindex="2" type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>', $templateCode);
	}else{
		$templateCode=str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		$templateCode=str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);
		$templateCode=str_replace('<%%DESELECT_BUTTON%%>', ($ShowCancel ? '<button tabindex="2" type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>' : ''), $templateCode);
	}

	// set records to read only if user can't insert new records and can't edit current record
	if(($selected_id && !$AllowUpdate && !$arrPerm[1]) || (!$selected_id && !$arrPerm[1])){
		$jsReadOnly .= "\tjQuery('#report').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#report_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('#turnover').replaceWith('<p class=\"form-control-static\" id=\"turnover\">' + (jQuery('#turnover').val() || '') + '</p>');\n";
		$jsReadOnly .= "\tjQuery('#payroll_tax').replaceWith('<p class=\"form-control-static\" id=\"payroll_tax\">' + (jQuery('#payroll_tax').val() || '') + '</p>');\n";
		$jsReadOnly .= "\tjQuery('#ni_contribution').replaceWith('<p class=\"form-control-static\" id=\"ni_contribution\">' + (jQuery('#ni_contribution').val() || '') + '</p>');\n";
		$jsReadOnly .= "\tjQuery('#business_rates').replaceWith('<p class=\"form-control-static\" id=\"business_rates\">' + (jQuery('#business_rates').val() || '') + '</p>');\n";
		$jsReadOnly .= "\tjQuery('#corporation_tax').replaceWith('<p class=\"form-control-static\" id=\"corporation_tax\">' + (jQuery('#corporation_tax').val() || '') + '</p>');\n";
		$jsReadOnly .= "\tjQuery('#other_tax').replaceWith('<p class=\"form-control-static\" id=\"other_tax\">' + (jQuery('#other_tax').val() || '') + '</p>');\n";
		$jsReadOnly .= "\tjQuery('#sum').replaceWith('<p class=\"form-control-static\" id=\"sum\">' + (jQuery('#sum').val() || '') + '</p>');\n";
		$jsReadOnly .= "\tjQuery('#ratio').replaceWith('<p class=\"form-control-static\" id=\"ratio\">' + (jQuery('#ratio').val() || '') + '</p>');\n";

		$noUploads = true;
	}

	// process combos
	$templateCode=str_replace('<%%COMBO(created)%%>', ($selected_id && !$arrPerm[3] ? '<p class="form-control-static">' . $combo_created->GetHTML(true) . '</p>' : $combo_created->GetHTML()), $templateCode);
	$templateCode=str_replace('<%%COMBOTEXT(created)%%>', $combo_created->GetHTML(true), $templateCode);
	$templateCode=str_replace('<%%COMBO(report)%%>', $combo_report->HTML, $templateCode);
	$templateCode=str_replace('<%%COMBOTEXT(report)%%>', $combo_report->MatchText, $templateCode);
	$templateCode=str_replace('<%%URLCOMBOTEXT(report)%%>', urlencode($combo_report->MatchText), $templateCode);

	// process foreign key links
	if($selected_id){
		$templateCode=str_replace('<%%PLINK(report)%%>', ($combo_report->SelectedData ? "<span id=\"reports_plink1\" class=\"hidden\"><a class=\"btn btn-default\" href=\"reports_view.php?SelectedID=" . urlencode($combo_report->SelectedData) . "\"><i class=\"glyphicon glyphicon-search\"></i></a></span>" : ''), $templateCode);
	}

	// process images
	$templateCode=str_replace('<%%UPLOADFILE(tax_entry_id)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(created)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(created_by)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(report)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(turnover)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(payroll_tax)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(ni_contribution)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(business_rates)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(corporation_tax)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(other_tax)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(sum)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(ratio)%%>', '', $templateCode);

	// process values
	if($selected_id){
		$templateCode=str_replace('<%%VALUE(tax_entry_id)%%>', htmlspecialchars($row['tax_entry_id'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(tax_entry_id)%%>', urlencode($urow['tax_entry_id']), $templateCode);
		$templateCode=str_replace('<%%VALUE(created)%%>', @date('d/m/Y', @strtotime(htmlspecialchars($row['created'], ENT_QUOTES))), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(created)%%>', urlencode(@date('d/m/Y', @strtotime(htmlspecialchars($urow['created'], ENT_QUOTES)))), $templateCode);
		$templateCode=str_replace('<%%VALUE(created_by)%%>', htmlspecialchars($row['created_by'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(created_by)%%>', urlencode($urow['created_by']), $templateCode);
		$templateCode=str_replace('<%%VALUE(report)%%>', htmlspecialchars($row['report'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(report)%%>', urlencode($urow['report']), $templateCode);
		$templateCode=str_replace('<%%VALUE(turnover)%%>', htmlspecialchars($row['turnover'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(turnover)%%>', urlencode($urow['turnover']), $templateCode);
		$templateCode=str_replace('<%%VALUE(payroll_tax)%%>', htmlspecialchars($row['payroll_tax'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(payroll_tax)%%>', urlencode($urow['payroll_tax']), $templateCode);
		$templateCode=str_replace('<%%VALUE(ni_contribution)%%>', htmlspecialchars($row['ni_contribution'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(ni_contribution)%%>', urlencode($urow['ni_contribution']), $templateCode);
		$templateCode=str_replace('<%%VALUE(business_rates)%%>', htmlspecialchars($row['business_rates'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(business_rates)%%>', urlencode($urow['business_rates']), $templateCode);
		$templateCode=str_replace('<%%VALUE(corporation_tax)%%>', htmlspecialchars($row['corporation_tax'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(corporation_tax)%%>', urlencode($urow['corporation_tax']), $templateCode);
		$templateCode=str_replace('<%%VALUE(other_tax)%%>', htmlspecialchars($row['other_tax'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(other_tax)%%>', urlencode($urow['other_tax']), $templateCode);
		$templateCode=str_replace('<%%VALUE(sum)%%>', htmlspecialchars($row['sum'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(sum)%%>', urlencode($urow['sum']), $templateCode);
		$templateCode=str_replace('<%%VALUE(ratio)%%>', htmlspecialchars($row['ratio'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(ratio)%%>', urlencode($urow['ratio']), $templateCode);
	}else{
		$templateCode=str_replace('<%%VALUE(tax_entry_id)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(tax_entry_id)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(created)%%>', '<%%creationDate%%>', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(created)%%>', urlencode('<%%creationDate%%>'), $templateCode);
		$templateCode=str_replace('<%%VALUE(created_by)%%>', '<%%creatorUsername%%>', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(created_by)%%>', urlencode('<%%creatorUsername%%>'), $templateCode);
		$templateCode=str_replace('<%%VALUE(report)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(report)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(turnover)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(turnover)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(payroll_tax)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(payroll_tax)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(ni_contribution)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(ni_contribution)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(business_rates)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(business_rates)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(corporation_tax)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(corporation_tax)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(other_tax)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(other_tax)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(sum)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(sum)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(ratio)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(ratio)%%>', urlencode(''), $templateCode);
	}

	// process translations
	foreach($Translation as $symbol=>$trans){
		$templateCode=str_replace("<%%TRANSLATION($symbol)%%>", $trans, $templateCode);
	}

	// clear scrap
	$templateCode=str_replace('<%%', '<!-- ', $templateCode);
	$templateCode=str_replace('%%>', ' -->', $templateCode);

	// hide links to inaccessible tables
	if($_POST['dvprint_x']==''){
		$templateCode.="\n\n<script>jQuery(function(){\n";
		$arrTables=getTableList();
		foreach($arrTables as $name => $caption){
			$templateCode .= "\tjQuery('#{$name}_link').removeClass('hidden');\n";
			$templateCode .= "\tjQuery('#xs_{$name}_link').removeClass('hidden');\n";
			$templateCode .= "\tjQuery('[id^=\"{$name}_plink\"]').removeClass('hidden');\n";
		}

		$templateCode .= $jsReadOnly;

		if(!$selected_id){
		}

		$templateCode.="\n});</script>\n";
	}

	// ajaxed auto-fill fields
	$templateCode.="<script>";
	$templateCode.="document.observe('dom:loaded', function() {";


	$templateCode.="});";
	$templateCode.="</script>";
	$templateCode .= $lookups;

	// handle enforced parent values for read-only lookup fields

	// don't include blank images in lightbox gallery
	$templateCode=preg_replace('/blank.gif" rel="lightbox\[.*?\]"/', 'blank.gif"', $templateCode);

	// don't display empty email links
	$templateCode=preg_replace('/<a .*?href="mailto:".*?<\/a>/', '', $templateCode);

	// hook: tax_entry_dv
	if(function_exists('tax_entry_dv')){
		$args=array();
		tax_entry_dv(($selected_id ? $selected_id : FALSE), getMemberInfo(), $templateCode, $args);
	}

	return $templateCode;
}
?>